# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.destroy_all
Category.destroy_all
ProductCategory.destroy_all


Category.create(name: "electronics") 
Category.create(name: "home") 
Category.create(name: "food & grocery") 
Category.create(name: "toys, kids & baby")
Category.create(name: "sports & outdoors") 
Category.create(name: "games")
Category.create(name: "beauty & health") 


1 Product.create(name: "Digital Camera, Lecran FHD 1080P 36.0 Mega Pixels Vlogging Camera with 16X Digital Zoom, LCD Screen, Compact Portable Mini Cameras for Students, Teens, Kids (Purple)", image: "https://images-na.ssl-images-amazon.com/images/I/71a5wNItTJL._AC_SL1500_.jpg", price: 48.99, description: "【FHD 1080P & 36MP Digital Camera】Featured with FHD 1080P resolution and 36.0 megapixels, this digital camera will help you to capture the most exciting memorable moments with good quality images or videoes. Totally fits your demand, you could have fun and record wonderful times with friends, family members, and classmates.")
2 Product.create(name: "Digital Camera Vlogging Camera 30MP Full HD 1080P Digital Camera with Retractable Flash Light Camera 3 Inch Flip Screen Vlog Camera for YouTube with Two Batteries(32GB Micro SD Card Included)", image: "https://images-na.ssl-images-amazon.com/images/I/61TnMFVbLWS._AC_SL1000_.jpg", price: 99.98, description: "The digital camera supports 2.7K video resolution and 30MP picture resolution with good image quality.This vlogging camera has 3 inch full frame view flip screen which can rotate at 180 degrees, you can take selfies easily. The camera also supports 4x digital zoom, which means you can zoom in or out of the picture for better capture of the details.")
3 Product.create(name: "Baby Monitor with Camera and Audio,Conico 1080P Pet Camera,Dog Camera with 2 Way Audio,Motion and Sound Detection,Night Vision,WiFi Camera Indoor Camera Work with Alexa for Baby Pet(2 Packs)", image: "https://images-na.ssl-images-amazon.com/images/I/61vQFdCJwhL._AC_SL1500_.jpg", price: 40.99, description: "1080P and 2-Megapixel:The video baby monitor is equipped with a 1080P camera and 2-megapixel,featuring 8x zoom,enable you capture hd videos and snapshot images.It could provide live streaming 24/7 with real-time motion to let you know what is going on for your home instantly.(please noticed:the home camera works with 2.4GHz Wi-Fi networks,Not 5GHz Wi-Fi)")
4 Product.create(name: "Blink Outdoor - wireless, weather-resistant HD security camera, two-year battery life, motion detection, set up in minutes – 2 camera kit", image: "https://images-na.ssl-images-amazon.com/images/I/61TRYGIDWkL._SL1000_.jpg", price: 179.99, description: "Blink Outdoor is a wireless battery-powered HD security camera that helps you monitor your home day or night with infrared night vision. With long-lasting battery life, Outdoor runs for up to two years on two AA lithium batteries (included). Outdoor is built to withstand the elements to help you protect your home inside or out, come rain or shine.")
5 Product.create(name: "VIZIO 70-Inch V-Series 4K UHD LED HDR Smart TV with Voice Remote, Apple AirPlay and Chromecast Built-in, Dolby Vision, HDR10+, HDMI 2.1, IQ Active Processor and V-Gaming Engine", image: "https://images-na.ssl-images-amazon.com/images/I/81CXQh-ANVS._AC_SL1500_.jpg", price: 649.99, description: "Dolby Vison HDR Watch your favorite content with the incredible brightness, contrast and color with support for Dolby Vision, HDR10+, and HLG high dynamic range formats. 4K Ultra HD With over 8 million pixels, 4 times the resolution of 1080p and pixel level brightness adjustments with Active Pixel Tuning- stream your favorite movies, TV shows, and game with breathtaking detail.")
6 Product.create(name: "Toshiba 43LF421U21 43-inch Smart HD 1080p TV - Fire TV, Released 2020", image: "https://images-na.ssl-images-amazon.com/images/I/61piX33QmAL._AC_SL1000_.jpg", price: 199.99, description: "Fire TV brings together live-over-the air TV and your streaming content on the home screen. Connect any HD antenna (sold separately) to watch live over-the-air TV or stream movies and shows from Disney+, Netflix, YouTube, Prime Video, Hulu, HBO and more. Everything you’d expect from a remote – plus launch apps, search for TV shows, switch inputs, control smart home devices and more, using just your voice. With Prime Video, Netflix and HBO buttons, instantly access your favorite apps.")
7 Product.create(name: "CyberpowerPC Gamer Xtreme VR Gaming PC, Intel i5-10400F 2.9GHz, GeForce GTX 1660 Super 6GB, 8GB DDR4, 500GB NVMe SSD, Wi-Fi Ready & Windows 10 Home (GXiVR8060A10)", image: "https://images-na.ssl-images-amazon.com/images/I/81Wx7hw9vwL._AC_SL1500_.jpg", price: 949.99, description: "System: Intel Core i5-10400F 2.9GHz 6-Core, Intel B460 Chipset, 8GB DDR4, 500GB PCI-E NVMe SSD, & Genuine Windows 10 Home 64-bit. NVIDIA GeForce GTX 1660 Super 6GB Video Card, 1x HDMI, & 1x DisplayPort. Connectivity: 6 x USB 3.1, 2 x USB 2.0, 1x RJ-45 Network Ethernet 10/100/1000, 802.11AC Wi-Fi. Audio: 7.1 Channel. Keyboard and mouse.")
8 Product.create(name: "Skytech Archangel Gaming Computer PC Desktop – Ryzen 5 3600 3.6GHz, GTX 1660 Super 6G, 500GB SSD, 16GB DDR4 3000MHz, RGB Fans, Windows 10 Home 64-bit, 802.11AC Wi-Fi", image: "https://images-na.ssl-images-amazon.com/images/I/71iWWhTYmPL._AC_SL1498_.jpg", price: 1249.99, description: "AMD Ryzen 5 3600 6-Core 12-Thread 3.6GHz (4.2 GHz Max Boost) CPU | 500GB SSD – Up to 30x faster than traditional HDD | B450 Motherboard. GeForce GTX 1660 Super 6GB GDDR6 Graphics Card (Brand May Varies) | 16GB DDR4 3000MHz Gaming Memory with Heat Spreaders | Windows 10 Home 64-bit | AMD High Performance Wraith Cooler. 802.11AC Wi-Fi | No Bloatware | Graphics Ports may Vary | HD Audio and Mic | Free Gaming Keyboard and Mouse | 2 x USB 3.0, 2 x USB 2.0, 4 x USB 3.2 Gen1.")
9 Product.create(name: "Cycle-Labs (US Based Business) 24, 26, 27.5 and 29 Inch Mountain Bike 21 Speed for Men Women Adult Hard Trail Front Suspension Disc Brakes Aluminum Steel Frame – Black and Yellow, Red, White", image: "https://images-na.ssl-images-amazon.com/images/I/71LX5Gt6Z3S._AC_SL1400_.jpg", price: 289.20, description: "HEAVY DUTY FRAME: Made from high-carbon steel and aluminum frame these bikes are durably made to long last offering you excellent service life. Enjoy a quick ride to your work space, neighbourhood rides, or trails on this cool Cycle Labs bike. 21 SPEED TRAIL BIKE: Features a wide gear range with 3 front derailleur and 7 rear derailleur which makes changing gears very smooth so you can easily handle uphill or downhill slopes. The front suspension shock-absorbers helps you to move easily on rough and bumpy tracks.")
10 Product.create(name: "Schwinn Wayfarer Adult Hybrid Bike Retro-Styled Cruiser, Step-Through and Step-Over Steel Frame, 7-Speed Drivetrain, Rear Rack, 700c Wheels, Multiple Colors", image: "https://m.media-amazon.com/images/I/71r9gjwJcdS._AC_SL1500_.jpg", price: 285.77, description: "Great for casual pavement and bike path riding, 700c wheels fit riders 64 to 74 inches tall. Schwinn retro city-style steel frame and steel fork are sturdy yet responsive. 7-speed twist shifters provide smooth gear changes. Front and rear alloy linear pull brakes provide crisp, efficient stopping. Swept-back handlebars offer a comfortable, upright riding position that's easier on your back.")
11 Product.create(name: "Coleshome 47 Inch Computer Desk, Modern Simple Style Desk for Home Office, Study Student Writing Desk,Black", image: "https://images-na.ssl-images-amazon.com/images/I/71e8mRs5VPS._AC_SL1500_.jpg", price: 51.99, description: "Modern Design with Stability: A sturdy desk designed with elegance. Thick metal frames & extra metal brackets ensure stability. Desktop is waterproof and anti-scratch, very easy to clean. Desk frame is made of heavy duty powder coated steel which ensures stability and durability. The desktop is thick enough to support heavy objects.")
12 Product.create(name: 'CubiCubi Study Computer Desk 40" Home Office Writing Small Desk, Modern Simple Style PC Table, Black Metal Frame, Rustic Brown', image: "https://images-na.ssl-images-amazon.com/images/I/716ExA--byL._AC_SL1500_.jpg", price: 49.89, description: "Modern Simple Desk: CubiCubi computer desk delivers a peaceful experience to you wherever at home or office. The rigid metal frame and raliable MDF boards give it a solid structure as well as beautiful appearance. With the extra storage bag and iron hook, you can easily organize your working stuffs.")
13 Product.create(name: "Gaming Computer Desk Z Shaped 43 inch PC Large Gaming Table, Racing Table, Student Desk, Home Office Desk Gamer Workstation with Cup Holder Headphone Hook for Kids Adults, White", image: "https://images-na.ssl-images-amazon.com/images/I/71XiLAm7uUS._AC_SL1500_.jpg", price: 59.96, description: "【Multifunctional large desk】 42.12” x26.57” gaming surface with a sleek carbon fiber texture, It can accommodate your monitor,  PC, gaming keyboards and other gaming gear. In addition, it is not only a gaming desk, also a multi-functional workstation. Suitable for all home office activity including writing work. You can work quietly at home.  It is the best choice as computer desk, study desk, gaming desk, etc. The desk comes with a convenient cup holder , headphone hook and two Cable Management hole.  Headphone hook provides spots for your gaming gears，and cup holder lets you keep a drink nearby without worrying about spilling. Multiple cable management tools centralize your wires and save space These plenty of convenient features help you to have a better gaming experience.")
14 Product.create(name: "Warheads Extreme Sour Hard Candy (Pack of 240)", image: "https://images-na.ssl-images-amazon.com/images/I/91Ukbf3B4SL._SL1500_.jpg", price: 26.94, description: "Warheads extreme sour candy will make you pucker up. Come in five assorted flavors including apple, black cherry, blue raspberry, lemon, and watermelon.")
15 Product.create(name: "JOLLY RANCHER Lollipops, Hard Candy and Stix Assorted Fruit Flavored Candy, Bulk, 46 oz Bag", image: "https://images-na.ssl-images-amazon.com/images/I/81ejyLp9uIL._SL1500_.jpg", price: 9.57, description: "Long-lasting JOLLY RANCHER candy you can take with you on the go, to work, on snack breaks and back home again at the end of the day. Fruit-flavored assorted candy individually wrapped for convenience and exceptional freshness to the last piece.")
16 Product.create(name: "Assorted Candy Bulk Individually Wrapped Candies Assortment - Huge Party Mix of Airheads, Skittles, Sour Punch, Swedish Fish, Nerds, Twizzlers and More (76 Count Variety Pack, Appx. 3.5 Lbs)", image: "https://images-na.ssl-images-amazon.com/images/I/91zX%2BICgPBL._SL1500_.jpg", price: 39.99, description: "Skip buying boxes of different snacks when you can enjoy a variety of 22 different snacks from your favorite brands in just one box! Assortment Includes Sour Punch, Skittles, Airheads, Laffy Taffy, Push Pop, Twizzlers, Now and Later, Dum Dum, Haribo, Lifesavers, Ring Pop, Gushers, Mott's Fruit Snacks, Nerds, Swedish Fish, Fun Dip and Fruit Roll-Ups. Grab one in the car, at work, packed for lunch or enjoy at home! Great for trips, parties, school, holidays and care packages. Conveniently packaged in individually wrapped pouches, these treats are travel-friendly and easy to stow in a lunchbox, backpack, or tote. bag.")
17 Product.create(name: "CANDYMAN Bundle of Chocolate Candy (5.6 lbs) Variety Pack Hersheys Nestles Reese's Snickers York Peppermint Almond Joy M&Ms Peanut and Milk Chocolate, 100 Grand Bars, Milky Way", image: "https://images-na.ssl-images-amazon.com/images/I/71Nl7UurxlL._SL1500_.jpg", price: 36.98, description: "Bundle of Office supplies candy deal of the day prime birthday gift baskets for women. The office merchandise bulk candy snacks variety premier chocolate gift box. Individually wrapped assorted candy bulk. Snacks variety pack vending machine.")
18 Product.create(name: "Wilson Evolution Game Basketball", image: "https://images-na.ssl-images-amazon.com/images/I/91vdgs5FY4L._AC_SL1500_.jpg", price: 64.99, description: "The number 1 indoor ball: The Evolution is the number 1 indoor game basketball in America, on more courts than any other basketball. Signature EVO feel: the soft feel that the evolution basketball is famous for is due it’s cushion core carcass, making the ball softer to the touch and easier to grip around the rim.")
19 Product.create(name: "Bedside Lamp with USB port - Touch Control Table Lamp for Bedroom Wood 3 Way Dimmable Nightstand Lamp with Round Flaxen Fabric Shade for Living Room, Kids Room, College Dorm, Office(LED Bulb Included)", image: "https://images-na.ssl-images-amazon.com/images/I/51F2Y0S7AaS._AC_SL1000_.jpg", price: 28.99, description: "These touch control dimmable table lamp is small in size which is really perfect to decorate anywhere of your house. A ideal USB table lamp for living room, bedroom, study room, kids room, etc. Add a bit of warm and comfortable atmosphere to your bedroom or living room. The dimmable bedside table lamp offers 3 level brightness options (Low, Medium, High).Just simply tap on anywhere of the metal base to adjust the lighting to meet your different needs. Nightlight for a steady sleep or nursing . Accent lighting for warm mood. Proper high comfortable brightness for studying or working. Super handy to operate.")
20 Product.create(name: "addlon LED Modern Shelf Floor Lamp with White Lamp Shade and LED Bulb - Display Shelves Floor Lamps for Living Room Bedroom and Office - Classic Black", image: "https://images-na.ssl-images-amazon.com/images/I/61Jffe%2B2uRS._AC_SL1500_.jpg", price: 42.49, description: "riple Storage Space: addlon Shelf floor lamp with 3 tiers storage space, each board use high-density fiber material, which loads 50 pounds max. You can put photo frame, plants, books, or any items on it. Also, the lamps self is heavy enough to avoid fall down. 50,000hrs LED Bulb: The shelf lamp comes with one 2700K LED bulb, which can provide 50,000hrs service life. It means you donot need change bulb for many years. Also, the LED bulb saves 50% electric bill per year than normal incandescent bulbs. Quality Lampshade with Soft Light: We provide a beautiful lampshade, it makes of high-quality fabric. The lighting through the lampshade becomes soft and gentle, which creates a cozy and comfortable atmosphere in the night.")
21 Product.create(name: "Furinno Turn-N-Tube 5 Tier Corner Shelf, Espresso/Black", image: "https://images-na.ssl-images-amazon.com/images/I/61t6G1jMD%2BL._AC_SL1500_.jpg", price: 24.14, description: "Simple stylish design yet Functional and suitable for any room. Great storage unit for bathroom, closet, home office, living room, kids room, kitchen, etc. Sturdy on flat surface and no hassle 5-minutes assembly.")
22 Product.create(name: "Aveeno Active Naturals Daily Moisturizing Lotion, 18 Ounce", image: "https://images-na.ssl-images-amazon.com/images/I/71fpYAPvK%2BL._SL1500_.jpg", price: 8.68, description: "18-fluid ounce pump bottle of Aveeno Daily Moisturizing Body Lotion to moisturize dry skin for a full 24 hours. Nourishing lotion contains a unique soothing oatmeal formula that absorbs quickly, leaving your skin soft, beautiful and healthy-looking. Clinically proven and award winning fragrance-free daily lotion for dry skin locks in moisture and improves skin's health in just 1 day.")
23 Product.create(name: "Neutrogena Hydro Boost Hyaluronic Acid Hydrating Water Gel Daily Face Moisturizer for Dry Skin, Oil-Free, Non-Comedogenic Face Lotion, 1.7 fl. oz", image: "https://images-na.ssl-images-amazon.com/images/I/71Bd6%2BBQQnL._SL1500_.jpg", price: 14.82, description: "1.7-fluid ounce jar of Neutrogena Hydro Boost hydrating water-gel face moisturizer with hyaluronic acid to hydrate dry skin. Gel moisturizer formula provides hydration to skin, leaving it looking smooth and supple day after day. Hyaluronic acid, a hydrator found naturally in the skin, attracts moisture and locks it in.")
24 Product.create(name: "GearLight LED Camping Lantern Sunlit (2 Pack) - Battery Powered Lamp Lanterns for Emergency, Power Outages, Hurricane – Portable Camp Light, Flashlights, Accessories, Gear, Supplies", image: "https://images-na.ssl-images-amazon.com/images/I/71xi%2BukgEDL._AC_SL1200_.jpg", price: 13.99, description: "Battery Operated, Super Bright, & Long-Lasting - The Sunlit Lantern's powerful upgraded COB LED design offers 360-degree blazing illumination that far outshines the standard 30 LED lantern. With just a single set of 3 AA batteries, you can experience the next best thing to actual daylight for hours of use. All-Weather Durability - Built for rough handling, it can survive accidental drops, as well as rain, snow, hurricanes, storms, or any other natural disaster. It is the ultimate reliable lighting accessory for outdoors, indoors, emergencies, power failure, camping, fishing, or even taking the kids out trick-or-treating.")
25 Product.create(name: "Amazon Basics 36 Pack AAA High-Performance Alkaline Batteries, 10-Year Shelf Life, Easy to Open Value Pack", image: "https://images-na.ssl-images-amazon.com/images/I/71nDX36Y9UL._AC_SL1026_.jpg", price: 10.99, description: "AAA 1.5-volt performance alkaline batteries; ideal for a variety of devices, including game controllers, toys, flashlights, digital cameras, and clocks. 10-year leak-free shelf life; air- and liquid-tight seal locks in the power until it’s needed thanks to the improved design, which includes dual crimps, a new zinc composition, and anti-corrosion components.")
26 Product.create(name: "", image: "", price: , description: "")
